fix：add ImageBitmap support.
flozz/StackBlur pull request #47
Opened 2023-05-16 07:09 UTC by Jason11Q

blur for texture source

2023-05-18 20:47 UTC, brettz9 commented on src/stackblur.js
> +  if (img instanceof HTMLImageElement && !('naturalWidth' in img)) {
`instanceof` doesn't work across frames, so I think it was better to just duck-type it...

2023-05-18 20:50 UTC, brettz9 commented on src/stackblur.js
> +  if (img instanceof ImageBitmap) {
Instead of `instanceof`, you could add `Object.prototype.toString.call(img).slice(8, -1) === 'ImageBitmap'`

2023-05-20 02:41 UTC, Jason11Q commented
Thanks, it‘s modified

2023-05-20 13:42 UTC, brettz9 requested changes

2023-05-20 13:42 UTC, brettz9 commented on src/stackblur.js
> +  // FIXED: JC change the attr condition better
Rather than adding attribution comments here and below, feel free to add yourself to `contributors` in `package.json`.

2023-05-20 13:42 UTC, brettz9 commented on src/stackblur.js
> +  // FIXED: JC add ImageBitmap support,can blur texture source
And here

2023-05-20 13:42 UTC, brettz9 commented on src/stackblur.js
> -  if (!img || !('naturalWidth' in img)) {
Please keep the `!img ||` condition in case it is a bad selector.

2023-06-01 10:09 UTC, Jason11Q commented
tk,gei it

2023-06-01 11:45 UTC, brettz9 requested changes

2023-06-01 11:45 UTC, brettz9 commented on src/stackblur.js
> +) {
Nit: Please avoid adding trailing whitespace

2023-06-01 11:45 UTC, brettz9 commented on src/stackblur.js
> +  }
Nit: Please avoid adding trailing whitespace

2023-06-05 03:55 UTC, merged